name: 'Setup luamake'
description: 'Build and setup luamake for different operating systems'
author: 'yuchanns'
branding:
  icon: activity
  color: purple

inputs:
  luamake-version:
    description: 'luamake tag or branch to checkout'
    required: false
    default: ''

outputs:
  luamake-path:
    description: 'Path to the luamake executable'
    value: ${{ steps.setup.outputs.luamake-path }}

runs:
  using: 'composite'
  steps:
    - id: binary-path
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          TARGET_DIR="C:/Windows/System32"
          LUAMAKE_BINARY="luamake.exe"
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          TARGET_DIR="/usr/local/bin"
          LUAMAKE_BINARY="luamake"
        else  # Linux
          TARGET_DIR="/usr/local/bin"
          LUAMAKE_BINARY="luamake"
        fi
        echo "target_dir=$TARGET_DIR" >> $GITHUB_OUTPUT
        echo "luamake_binary=$LUAMAKE_BINARY" >> $GITHUB_OUTPUT

    - name: Cache luamake
      uses: actions/cache@v4
      id: cache
      with:
        path: |
          ${{steps.binary-path.outputs.target_dir}}/${{ steps.binary-path.outputs.luamake_binary }}
          ${{steps.binary-path.outputs.target_dir}}/main.lua
          ${{steps.binary-path.outputs.target_dir}}/scripts
        key: ${{ runner.os }}-luamake-${{ inputs.luamake-version }}

    - name: Checkout luamake source with submodules
      uses: actions/checkout@v4
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        repository: 'actboy168/luamake'
        ref: ${{ inputs.luamake-version }}
        submodules: recursive
        path: .luamake-temp

    - name: Setup dependencies (Linux)
      if: runner.os == 'Linux' && steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt update
        sudo apt install gcc g++ ninja-build binutils-dev libunwind-dev -y

    - name: Setup MSVC (Windows)
      if: runner.os == 'Windows' && steps.cache.outputs.cache-hit != 'true'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build luamake
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      working-directory: .luamake-temp
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          chmod +x compile/install.bat 2>/dev/null || true
          compile/install.bat
        else
          chmod +x compile/install.sh
          compile/install.sh
        fi

    - name: Install luamake to system and cleanup
      id: setup
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      env:
        TARGET_DIR: ${{ steps.binary-path.outputs.target_dir }}
        LUAMAKE_BINARY: ${{ steps.binary-path.outputs.luamake_binary }}
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          echo "Using Windows system directory: $TARGET_DIR"
        else
          sudo mkdir -p "$TARGET_DIR" 2>/dev/null || mkdir -p "$TARGET_DIR"
        fi
        
        if [ -f ".luamake-temp/$LUAMAKE_BINARY" ]; then
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            cp ".luamake-temp/$LUAMAKE_BINARY" "$TARGET_DIR/"
            cp ".luamake-temp/main.lua" "$TARGET_DIR/"
            cp -r ".luamake-temp/scripts" "$TARGET_DIR/"
          else
            sudo cp ".luamake-temp/$LUAMAKE_BINARY" "$TARGET_DIR/" 2>/dev/null || cp ".luamake-temp/$LUAMAKE_BINARY" "$TARGET_DIR/"
            sudo cp ".luamake-temp/main.lua" "$TARGET_DIR/" 2>/dev/null || cp ".luamake-temp/main.lua" "$TARGET_DIR/"
            sudo cp -r ".luamake-temp/scripts" "$TARGET_DIR/" 2>/dev/null || cp -r ".luamake-temp/scripts" "$TARGET_DIR/"
            sudo chmod +x "$TARGET_DIR/$LUAMAKE_BINARY" 2>/dev/null || chmod +x "$TARGET_DIR/$LUAMAKE_BINARY"
          fi
          echo "luamake-path=$TARGET_DIR" >> $GITHUB_OUTPUT
          echo "✅ luamake installed to $TARGET_DIR"
        else
          echo "❌ luamake binary not found at .luamake-temp/$LUAMAKE_BINARY"
          ls -la .luamake-temp/
          exit 1
        fi
        
        rm -rf .luamake-temp
        echo "🧹 Cleaned up source directory"
    - name: Verify luamake installation 
      shell: bash
      run: |
        which luamake || echo "Checking luamake installation..."
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          where luamake || echo "luamake.exe installed to $TARGET_DIR"
        fi
        luamake help
